language: php
php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - "$HOME/.composer/cache"

before_script:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - travis_retry composer tests